// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "f0d22d28-2c27-421f-82d0-07520da216d3");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1679496760);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1679496745);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1679496741);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1679496880);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1679496789);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{01b2f1e1-717f-422f-9bab-3caf2221fb69}");
user_pref("browser.download.lastDir", "/home/isp-1/Загрузки");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1679496729);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 133);
user_pref("browser.newtabpage.activity-stream.impressionId", "{b332d8de-cb2e-436c-bf8d-09275ecf9a9b}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1679496735);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1679496808400");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1679498582400");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1679496745719");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1679518345719");
user_pref("browser.search.region", "RU");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230214170610");
user_pref("browser.startup.homepage_override.mstone", "110.0");
user_pref("browser.startup.lastColdStartupCheck", 1679496733);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":18,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1679496739684");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "110.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "RU");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "346b1b64ae124b22bac9b8df900a1fd0");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1679496731);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-ru@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20230214170610");
user_pref("extensions.lastAppVersion", "110.0");
user_pref("extensions.lastPlatformVersion", "110.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"24191ed6-983f-4a96-bb0c-1f0b9a2e2ea4\",\"pictureinpicture@mozilla.org\":\"8b083102-d861-46e4-a723-c0fccb453af5\",\"screenshots@mozilla.org\":\"dd5fb99d-99e7-4dd4-aada-14078dc9ddc8\",\"webcompat-reporter@mozilla.org\":\"4e8dff53-9043-42c7-8a85-88aa54b6c4c5\",\"webcompat@mozilla.org\":\"73be0cdc-878a-4c17-8139-8d600485b557\",\"default-theme@mozilla.org\":\"38c559e5-36f5-41c9-bfa0-40200e4e12db\",\"addons-search-detection@mozilla.com\":\"9f1e4efe-947c-4f55-a4d1-b65cd33e3ebf\",\"google@search.mozilla.org\":\"2b4fbb78-1cbb-47b4-974b-56c86643ead4\",\"wikipedia@search.mozilla.org\":\"6d6e5f4d-52e2-49f8-9e0c-05e6d6ddab23\",\"ddg@search.mozilla.org\":\"b9ec9e23-fb21-402c-984b-8ffc7a91c8c0\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1679496744);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "3af0b7d6-81b2-4acc-8684-bec3080f80c5");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1679496721);
user_pref("toolkit.telemetry.cachedClientID", "7fbeb8c3-12e0-454e-9f0a-8efe2d16b56c");
user_pref("toolkit.telemetry.previousBuildID", "20230214170610");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
